name: MinecartMania
main: com.afforess.minecartmania.MinecartMania
version: 2.0 Beta
author: jrbudda, mze9412, Afforess
database: true
commands:
  mm:
    description: Base MM command class
    usage: /<command>
  st:
    description: Sets the station value, for any station intersection the players may pass in a minecart
    usage: /<command>
  trucompass:
    description: Returns the true compass direction for the direction that the player is facing
    usage: /<command>
permissions:
    minecartmania.*:
        description: Gives access to all minecart mania functionality
        default: op
        children:
            minecartmania.commands.*: true
            minecartmania.signs.*: true
    minecartmania.signs.*:
        description: Gives access to all minecart mania signs functionality
        default: true
        children:
             minecartmania.signs.create.*: true
             minecartmania.signs.break.*: true
    minecartmania.commands.*:
        description: Gives access to all minecart mania commands
        default: op
        children:
            minecartmania.commands.eject: true
            minecartmania.commands.permeject: true
            minecartmania.commands.clearemptycarts: true
            minecartmania.commands.clearpoweredcarts: true
            minecartmania.commands.clearstoragecarts: true
            minecartmania.commands.clearoccupiedcarts: true
            minecartmania.commands.clearallcarts: true
            minecartmania.commands.clearstalledcarts: true
            minecartmania.commands.clearmovingcarts: true
            minecartmania.commands.redraw: true
            minecartmania.commands.hide: true
            minecartmania.commands.momentum: true
            minecartmania.commands.info: true
            minecartmania.commands.trucompass: true
            minecartmania.commands.st: true
            minecartmania.commands.throttle: true
            minecartmania.commands.reload: true
    minecartmania.commands.eject:
        description: Ejects the given player from a minecart, if they are in one. 
        default: op
    minecartmania.commands.permeject:
        description: Ejects the given player from a minecart, and prevents them from re-entering any minecart. This resets if the command is used again for the given player, or if the server is restarted. 
        default: op
    minecartmania.commands.clearemptycarts:
        description: Removes all empty minecarts from the server. If -d (destroy) is set, they will not be returned to their owners. If the range is set, only carts inside the range will be cleared. 
        default: op
    minecartmania.commands.clearpoweredcarts:
        description: Removes all powered minecarts from the server. If -d (destroy) is set, they will not be returned to their owners. If the range is set, only carts inside the range will be cleared. 
        default: op
    minecartmania.commands.clearstoragecarts:
        description: Removes all storage minecarts from the server. If -d (destroy) is set, they will not be returned to their owners. If the range is set, only carts inside the range will be cleared. 
        default: op
    minecartmania.commands.clearoccupiedcarts:
        description: Removes all occupied minecarts from the server, dropping players where they stand. If -d (destroy) is set, they will not be returned to their owners. If the range is set, only carts inside the range will be cleared. 
        default: op
    minecartmania.commands.clearallcarts:
        description: Removes all minecarts from the server. If -d (destroy) is set, they will not be returned to their owners. If the range is set, only carts inside the range will be cleared. 
        default: op
    minecartmania.commands.clearstalledcarts:
        description: Removes any unmoving minecarts from the server. If -d (destroy) is set, they will not be returned to their owners. If the range is set, only carts inside the range will be cleared. 
        default: op
    minecartmania.commands.clearmovingcarts:
        description: Removes any moving minecarts from the server. If -d (destroy) is set, they will not be returned to their owners. If the range is set, only carts inside the range will be cleared. 
        default: op
    minecartmania.commands.redraw:
        description: Sends updates to all connected players to force all clients to redraw minecarts. Causes ~1 second of lag. 
        default: op
    minecartmania.commands.redraw:
        description: Sends updates to all connected players to force all clients to redraw minecarts. Causes ~1 second of lag. 
        default: op
    minecartmania.commands.hide:
        description: Hides all minecarts from view. They will continue moving, but will drop any passengers, and can not be seen unless someone re-logins or /mm redraw is used. 
        default: op
    minecartmania.commands.setconfigkey:
        description: Sets the given configuration key to the given value. The key name and value are case-sensitive. 
        default: op
    minecartmania.commands.help:
        description: Sends updates to all connected players to force all clients to redraw minecarts. Causes ~1 second of lag. 
        default: true
    minecartmania.commands.momentum:
        description: shows the momentum of the minecart the player is in. 
        default: true
    minecartmania.commands.info:
        description: Shows a list of detailed minecart information for the server 
        default: true
    minecartmania.commands.getconfigkey:
        description: shows the value of the given configuration key. The Key is case-sensitive. 
        default: true
    minecartmania.commands.listconfigkeys:
        description: Lists all of the config keys, in a page by page format 
        default: true
    minecartmania.commands.trucompass:
        description: Shows the true (Notch) direction that the player is facing. 
        default: true
    minecartmania.commands.st:
        description: Sets the station value for the player. It must be followed by any string, with numbers and letters. The -s flag saves the value so that it is not reset after 1 station. 
        default: true
    minecartmania.commands.throttle:
        description: Autocart Only. Changes the momentum of the minecart. 100% is normal max speed. Can not exceed 500%. 
        default: true
    minecartmania.signs.create.*:
        description: Gives access to all minecart mania create signs functionality
        default: true
        children:
            minecartmania.signs.create.launchersign: true
            minecartmania.signs.create.launchplayersign: true
            minecartmania.signs.create.holdingsign: true
            minecartmania.signs.create.alterrangesign: true
            minecartmania.signs.create.announcementsign: true
            minecartmania.signs.create.ejectionsign: true
            minecartmania.signs.create.ejectatsign: true
            minecartmania.signs.create.ejectionconditionsign: true
            minecartmania.signs.create.elevatorsign: true
            minecartmania.signs.create.lockcartsign: true
            minecartmania.signs.create.unlockcartsign: true
            minecartmania.signs.create.maxspeedsign: true
            minecartmania.signs.create.setstationsign: true
            minecartmania.signs.create.stopatdestinationsign: true
            minecartmania.signs.create.minecarttypesign: true
            minecartmania.signs.create.autotillsign: true
            minecartmania.signs.create.tilloffsign: true
            minecartmania.signs.create.autoseedsign: true
            minecartmania.signs.create.seedoffsign: true
            minecartmania.signs.create.autoharvestsign: true
            minecartmania.signs.create.harvestoffsign: true
            minecartmania.signs.create.autosugarsign: true
            minecartmania.signs.create.sugaroffsign: true
            minecartmania.signs.create.autoresugarsign: true
            minecartmania.signs.create.resugaroffsign: true
            minecartmania.signs.create.autotimbersign: true
            minecartmania.signs.create.timberoffsign: true
            minecartmania.signs.create.autoforestsign: true
            minecartmania.signs.create.forestoffsign: true
            minecartmania.signs.create.autocactussign: true
            minecartmania.signs.create.cactusoffsign: true
            minecartmania.signs.create.autorecactussign: true
            minecartmania.signs.create.recactusoffsign: true
            minecartmania.signs.create.farmsign: true
            minecartmania.signs.create.jumpsign: true
            minecartmania.signs.create.setspeedsign: true
    minecartmania.signs.create.launchersign:
        description: Create launch direction signs
        default: true
    minecartmania.signs.create.launchplayersign:
        description: Create launch player signs
        default: true
    minecartmania.signs.create.holdingsign:
        description: Create holding signs
        default: true
    minecartmania.signs.create.alterrangesign:
        description: Create Launch signs
        default: true
    minecartmania.signs.create.launchersign:
        description: Create alter range signs
        default: true
    minecartmania.signs.create.announcementsign:
        description: Create announcement signs
        default: true
    minecartmania.signs.create.ejectionsign:
        description: Create eject here signs
        default: true
    minecartmania.signs.create.ejectatsign:
        description: Create eject at signs
        default: true
    minecartmania.signs.create.ejectionconditionsign:
        description: Create ejection condition signs
        default: true
    minecartmania.signs.create.elevatorsign:
        description: Create elevator signs
        default: true
    minecartmania.signs.create.lockcartsign:
        description: Create lock cart signs
        default: true
    minecartmania.signs.create.launchersign:
        description: Create Launch signs
        default: true
    minecartmania.signs.create.unlockcartsign:
        description: Create unlock cart signs
        default: true
    minecartmania.signs.create.maxspeedsign:
        description: Create max speed signs
        default: true
    minecartmania.signs.create.setstationsign:
        description: Create set station signs
        default: true
    minecartmania.signs.create.stopatdestinationsign:
        description: Create stop at destination signs
        default: true
    minecartmania.signs.create.minecarttypesign:
        description: Create minecart type signs
        default: true
    minecartmania.signs.create.autotillsign:
        description: Create auto till signs
        default: true
    minecartmania.signs.create.tilloffsign:
        description: Create till off signs
        default: true
    minecartmania.signs.create.autoseedsign:
        description: Create auto seed signs
        default: true
    minecartmania.signs.create.seedoffsign:
        description: Create seed off signs
        default: true
    minecartmania.signs.create.autoharvestsign:
        description: Create auto harvest signs
        default: true
    minecartmania.signs.create.harvestoffsign:
        description: Create harvest off signs
        default: true
    minecartmania.signs.create.autosugarsign:
        description: Create auto sugar signs
        default: true
    minecartmania.signs.create.sugaroffsign :
        description: Create sugar off signs
        default: true
    minecartmania.signs.create.autoresugarsign:
        description: Create auto re sugar signs
        default: true
    minecartmania.signs.create.resugaroffsign:
        description: Create re sugar off signs
        default: true
    minecartmania.signs.create.autotimbersign:
        description: Create auto timber signs
        default: true
    minecartmania.signs.create.timberoffsign:
        description: Create timber off signs
        default: true
    minecartmania.signs.create.autoforestsign:
        description: Create auto forest signs
        default: true
    minecartmania.signs.create.forestoffsign:
        description: Create forest off signs
        default: true
    minecartmania.signs.create.autocactussign:
        description: Create auto cactus signs
        default: true
    minecartmania.signs.create.cactusoffsign:
        description: Create cactus off signs
        default: true
    minecartmania.signs.create.autorecactussign:
        description: Create auto recactus signs
        default: true
    minecartmania.signs.create.recactusoffsign:
        description: Create re cactus off signs
        default: true
    minecartmania.signs.create.farmsign:
        description: Create farm signs
        default: true
    minecartmania.signs.create.setspeedsign:
        description: Create set speed signs
        default: true
    minecartmania.signs.create.jumpsign:
        description: Create jump signs
        default: true